version: '3'

services:
  nginx:
    container_name: test_nginx
    image: nginx:1.17.4-alpine
    restart: always
    ports:
      - 89:80
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:cached
      - ./www/laravel:/var/www/app:cached
    depends_on:
      - php-fpm
      - node_front

  db:
    container_name: test_db
    image: mysql:5.7
    restart: always
    ports:
      - 3308:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=testwork
      - MYSQL_USER=test
      - MYSQL_PASSWORD=pass
    volumes:
      - ./mysql:/var/lib/mysql:cached

  php-fpm:
    container_name: test_php-fpm
    image: ishaburov/laravel_php-fpm7.4
    restart: always
    volumes:
      - ./www/laravel/:/var/www/app:cached
    working_dir: /var/www/app
    depends_on:
      - db

  laravel_cron:
    container_name: test_laravel_cron
    build:
      context: ./
      dockerfile: laravel_cron.dockerfile
    restart: always
    working_dir: /var/www/app
    volumes:
      - ./www/laravel/:/var/www/app:cached
    depends_on:
      - db

  node_front:
    container_name: test_node
    image: node:10
    volumes:
      - ./www/front/:/var/www/front/:cached
    working_dir: /var/www/front/
    command: yarn run start
